server:
  port: 8181

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: resourceService
          uri: lb://resource-service
          predicates:
            - Path=/api/v1/resources/**
          filters:
            - RewritePath=/api/v1/resources/actuator/prometheus, /actuator/prometheus

        - id: songService
          uri: lb://song-service
          predicates:
            - Path=/api/v1/song/**
          filters:
            - RewritePath=/api/v1/song/actuator/prometheus, /actuator/prometheus

        - id: storageService
          uri: lb://storage-service
          predicates:
            - Path=/api/v1/storages/**
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA:localhost}:8761/eureka
