server:
  port: 8181

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: resourceService
          uri: lb://resource-service
          predicates:
            - Path=/api/v1/resources/**
        - id: songService
          uri: lb://song-service
          predicates:
            - Path=/api/v1/song/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
